---
title: "The Self Criticism Relational Response Task (RRT-SC) – Validation of an Indirect Measure of Self-Criticism"
shorttitle: "RRTSC1 - Study Summary"
author: 
  - name:  Michael Pinus
    affiliation: 1
    corresponding: no    # Define only one corresponding author
    department: "Department Psychology"
    address: "Department Psychology, Ben-Gurion University in the Negev, Israel"
    email: "pinusm@post.bgu.ac.il"
  - name:  Golan Shahar
    affiliation: 1
    corresponding: no    # Define only one corresponding author
    department:
    address: "Department Psychology, Ben-Gurion University in the Negev, Israel"
    email: "pinusm@post.bgu.ac.il"
  - name:  Yoav Bar-Anan
    affiliation: 1
    corresponding: no    # Define only one corresponding author
    department:
    address: "Department Psychology, Ben-Gurion University in the Negev, Israel"
    email: "pinusm@post.bgu.ac.il"
affiliation:
  - id: 1
    institution: "Ben-Gurion University in the Negev"
#abstract: |
  
note: |  
  
  This document was created in Rmarkdown using `papaja` https://github.com/crsh/papaja.
floatsintext      : no
figurelist        : no
tablelist         : no
footnotelist      : no
linenumbers       : yes
mask              : no
draft             : yes
documentclass     : "apa6"
classoption       : "man"
output            : papaja::apa6_word
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
includePrev = F
knitr::opts_chunk$set(echo = F,
                      tidy = "styler",
                      cache = TRUE)

suppressPackageStartupMessages({
  library(magrittr) # A Forward-Pipe Operator for R
  library(lubridate) # Make Dealing with Dates a Little Easier
  library(tidyverse) # Easily Install and Load the 'Tidyverse'
  library(conflicted) # An Alternative Conflict Resolution Strategy
  library(Mmisc) # Some Helper Functions for Michael's Code
  library(RColorBrewer) # ColorBrewer Palettes
  library(BayesFactor) # Computation of Bayes Factors for Common Designs
  library(parameters) # Processing of Model Parameters
  library(ggpubr) # 'ggplot2' Based Publication Ready Plots
  library(patchwork) # The Composer of Plots
  library(psych)
  library(stargazer) # Well-Formatted Regression and Summary Statistics Tables
  library(see) # Visualisation Toolbox for 'easystats' and Extra Geoms, Themes and Color Palettes for 'ggplot2'
  library(papaja) # Prepare reproducible APA journal articles with R Markdown
  library(interactions)
  library(corx)
  library(effectsize)
  library(jtools)
})

options(digits = 3)
conflicted::conflict_prefer("filter", "dplyr", quiet = T)
conflicted::conflict_prefer("select", "dplyr", quiet = T)
```


## Data import
```{r, include=includePrev}
allds_item <- fst::read_fst("data/allds_item.fst")
RRTSC1 <- fst::read_fst("data/RRTSC1.fst")
home <- fst::read_fst("data/home.fst")
cleanImplicit <- fst::read_fst("data/cleanImplicit.fst")
latencies <- fst::read_fst("data/latencies.fst")
counterr <- fst::read_fst("data/counterr.fst")
counterrSorted <- fst::read_fst("data/counterrSorted.fst")
blocks <- fst::read_fst("data/blocks.fst")

male.list <- RRTSC1 %>% filter(female == 0) %>% pull(sbj)
female.list <- RRTSC1 %>% filter(female == 1) %>% pull(sbj)
```

# [OSF](https://osf.io/62qht/)

```{r, eval=FALSE}
# packages <- c("papaja", "RPushbullet","MASS","Hmisc", "plyr", "dplyr", "dtplyr", "foreign", "psych","car", "pwr", "xtable", "pequod", "IAT", "tidyr", "knitr", "purrr", "tibble", "sfsmisc")
```


```{r, include=includePrev}
## Participants 
completedPs <- length(na.omit(home$Finished))
totalPs <- length(unique(cleanImplicit$subject_nr))
completedPsPercent <-  round(100*length(na.omit(home$Finished))/length(unique(cleanImplicit$subject_nr)))
completedPsFemale <- length(na.omit(home$Finished[home$sbj %in% female.list]))
completedPsFemalePercent <-  round(100*length(na.omit(home$Finished[home$sbj %in% female.list]))/length(na.omit(home$Finished)))
# get age of all sample
describe_distribution(RRTSC1$age)
# get age of completed sample
describe_distribution(RRTSC1 %>% filter(sbj %in% home$sbj))

# count females in total sample
PsFemale <- length(female.list)
PsFemalePercent <-  round(100*PsFemale/totalPs)

```


```{r, results='asis', include=includePrev}
## Questionnaire Data 
describe_distribution(RRTSC1 %>% select(`SC-RRT` = RRT, 
                                        `BSI General` = BSI.general, 
                                        `BSI Depression` = BSI.Depression, 
                                        CESD = cesd,
                                        `DEQ-SC6` = deq6, 
                                        `FSCRS HS` = fscrsHS, 
                                        `FSCRS IS` = fscrsIS, 
                                        `FSCRS RS` = fscrsRS, 
                                        `FSCRS General` = fscrsGen, 
                                        RSES = rses)) %>%
        mutate(across(where(is.numeric),~round(.x,2))) %>% 
        select(-n,-n_Missing) %>% 
        apa_table(caption = "Descriptives for the questionnaires") %>%
        {.}
```

## RRT Data
```{r rrt data ttest, echo = FALSE, include=includePrev}
D.t.test <- t.test(RRTSC1$RRT,mu=0)
D.t.test %>% parameters()
t_to_d(D.t.test$statistic, D.t.test$parameter)
```

```{r, include=includePrev}
#mean latencies and error rates in blue and orange trials
latencies %>% 
  filter(blockno %in% c(3,4,6,7)) %>% 
  select(subject_nr ,trial_latency, stim_color, err) %>%
  group_by(subject_nr, stim_color) %>% 
  summarise(meanRT = mean(trial_latency), meanErr = mean(err)) %>% 
  group_by(stim_color) %>% 
  summarise(meanRT2 = mean(meanRT), sdRT = sd(meanRT, na.rm = T),
            meanErr2 = mean(meanErr), sdErr = sd(meanErr, na.rm = T)) %>% 
  mutate(across(where(is.numeric),round,2))


  
rt.lmm <- latencies %>% 
  filter(blockno %in% c(3,4,6,7)) %>% 
  select(subject_nr ,trial_latency, stim_color, err) %>%
  mutate(stim_color=fct_rev(stim_color)) %>% 
  # group_by(subject_nr, stim_color) %>% 
  lme4::lmer(data = . , formula = trial_latency ~ stim_color + (1|subject_nr)) 

# rt.lmm %>% 
#   summ 
# rt.lmm %>% 
#   report 

# with a t-test instead
  # latencies %>% 
  # filter(blockno %in% c(3,4,6,7)) %>% 
  # select(subject_nr ,trial_latency, stim_color, err) %>%
  # group_by(subject_nr, stim_color) %>% 
  # summarise(meanRT = mean(trial_latency)) %>% 
  # pivot_wider(names_from = stim_color, values_from = meanRT) %$% 
  # t.test(x = blue, y = orange, paired = T) %>% 
  #   # summary %>% 
  # {.} %>% 
  #   apa_print.htest()
  
err.glmm <- latencies %>% 
  filter(blockno %in% c(3,4,6,7)) %>% 
  select(subject_nr ,trial_latency, stim_color, err) %>%
  mutate(stim_color=fct_rev(stim_color)) %>% 
  lme4::glmer(data = . , formula = err ~ stim_color + (1|subject_nr),family = binomial(link = "logit")) 

# err.glmm %>% 
#   summ 
# err.glmm %>% 
#   report 

# with a t-test instead
  #   latencies %>% 
  # filter(blockno %in% c(3,4,6,7)) %>% 
  # select(subject_nr ,trial_latency, stim_color, err) %>%
  # group_by(subject_nr, stim_color) %>% 
  # summarise(meanErr = mean(err)) %>% 
  # pivot_wider(names_from = stim_color, values_from = meanErr) %$% 
  # t.test(x = blue, y = orange, paired = T) %>% 
  #   # summary %>% 
  # {.} %>% 
  #   apa_print.htest()

```


```{r, results='asis', include=includePrev}
## Correlation Analyses
corx(RRTSC1 %>% select(
    `SC-RRT` = RRT,
    `BSI Global` = BSI.general,
    `BSI Depression` = BSI.Depression,
    CESD = cesd,
    `DEQ-SC6` = deq6,
    RSES = rses,
    `FSCRS HS` = fscrsHS,
    `FSCRS IS` = fscrsIS,
    `FSCRS RS` = fscrsRS,
  ),
  triangle = "lower",
  stars = c(0.05, 0.01, 0.001)) %>%
  extract2("apa") %>%
  papaja::apa_table(caption = "Correlations of Questionnaire Scores",
                    note = "* p < 0.05; ** p < 0.01; *** p < 0.001",
                    escape = F) %>%
  {.}
```


```{r, include=includePrev}
## Reliabiliy Analyses

DEQ6q                 <- c("DEQ6.Q01" , "DEQ6.Q02" , "DEQ6.Q03" , "DEQ6.Q04" , "DEQ6.Q05" , "DEQ6.Q06")
RSESq                 <- c("RSES.Q01" , "RSES.Q03" , "RSES.Q04" , "RSES.Q07" , "RSES.Q10" , "RSES.Q02r" , "RSES.Q05r" , "RSES.Q06r" , "RSES.Q08r" , "RSES.Q09r")
fscrsHS               <- c("FSCRS.Q09" , "FSCRS.Q10" , "FSCRS.Q12" , "FSCRS.Q15" , "FSCRS.Q22")
fscrsRS               <- c("FSCRS.Q03r" , "FSCRS.Q05r" , "FSCRS.Q08r" , "FSCRS.Q11r" , "FSCRS.Q13r" , "FSCRS.Q16r" , "FSCRS.Q19r" , "FSCRS.Q21r")
fscrsIS               <- c("FSCRS.Q01" , "FSCRS.Q02" , "FSCRS.Q04" , "FSCRS.Q06" , "FSCRS.Q07" , "FSCRS.Q14" , "FSCRS.Q17" , "FSCRS.Q18" , "FSCRS.Q20")
fscrsGen              <- c("FSCRS.Q09" , "FSCRS.Q10" , "FSCRS.Q12" , "FSCRS.Q15" , "FSCRS.Q22" , "FSCRS.Q03r" , "FSCRS.Q05r" , "FSCRS.Q08r" , "FSCRS.Q11r" , "FSCRS.Q13r" , "FSCRS.Q16r" , "FSCRS.Q19r" , "FSCRS.Q21r" , "FSCRS.Q01" , "FSCRS.Q02" , "FSCRS.Q04" , "FSCRS.Q06" , "FSCRS.Q07" , "FSCRS.Q14" , "FSCRS.Q17" , "FSCRS.Q18" , "FSCRS.Q20")
CESDq                 <- c("CESD.Q01" , "CESD.Q02" , "CESD.Q03" , "CESD.Q05" , "CESD.Q06" , "CESD.Q07" , "CESD.Q09" , "CESD.Q10" , "CESD.Q11" , "CESD.Q13" , "CESD.Q14" , "CESD.Q15" , "CESD.Q17" , "CESD.Q18" , "CESD.Q19" , "CESD.Q20" , "CESD.Q04r" , "CESD.Q08r" , "CESD.Q12r" , "CESD.Q16r")
BSI.Somatization      <- c("BSI.Q02" , "BSI.Q07" , "BSI.Q23" , "BSI.Q29" , "BSI.Q30" , "BSI.Q37")
BSI.OCD               <- c("BSI.Q05" , "BSI.Q15" , "BSI.Q26" , "BSI.Q27" , "BSI.Q32" , "BSI.Q36")
BSI.IntrprsnlSen      <- c("BSI.Q20" , "BSI.Q21" , "BSI.Q22" , "BSI.Q42")
BSI.Anxiety           <- c("BSI.Q01" , "BSI.Q12" , "BSI.Q19" , "BSI.Q38" , "BSI.Q45" , "BSI.Q49")
BSI.Depression        <- c("BSI.Q09" , "BSI.Q16" , "BSI.Q17" , "BSI.Q18" , "BSI.Q35" , "BSI.Q50")
BSI.Hostility         <- c("BSI.Q06" , "BSI.Q13" , "BSI.Q40" , "BSI.Q41" , "BSI.Q46")
BSI.PhobicAnxiety     <- c("BSI.Q08" , "BSI.Q28" , "BSI.Q31" , "BSI.Q43" , "BSI.Q47")
BSI.ParanoidIdeation  <- c("BSI.Q04" , "BSI.Q10" , "BSI.Q24" , "BSI.Q48" , "BSI.Q51")
BSI.Psychoticism      <- c("BSI.Q03" , "BSI.Q14" , "BSI.Q34" , "BSI.Q44" , "BSI.Q53")
BSI.general           <- c("BSI.Q01" , "BSI.Q02" , "BSI.Q03" , "BSI.Q04" , "BSI.Q05" , "BSI.Q06" , "BSI.Q07" , "BSI.Q08" , "BSI.Q09" , "BSI.Q10" , "BSI.Q11" , "BSI.Q12" , "BSI.Q13" , "BSI.Q14" , "BSI.Q15" , "BSI.Q16" , "BSI.Q17" , "BSI.Q18" , "BSI.Q19" , "BSI.Q20" , "BSI.Q21" , "BSI.Q22" , "BSI.Q23" , "BSI.Q24" , "BSI.Q25" , "BSI.Q26" , "BSI.Q27" , "BSI.Q28" , "BSI.Q29" , "BSI.Q30" , "BSI.Q31" , "BSI.Q32" , "BSI.Q33" , "BSI.Q34" , "BSI.Q35" , "BSI.Q36" , "BSI.Q37" , "BSI.Q38" , "BSI.Q39" , "BSI.Q40" , "BSI.Q41" , "BSI.Q42" , "BSI.Q43" , "BSI.Q44" , "BSI.Q45" , "BSI.Q46" , "BSI.Q47" , "BSI.Q48" , "BSI.Q49" , "BSI.Q50" , "BSI.Q51" , "BSI.Q52" , "BSI.Q53")
BSI.withoutOCD        <- c("BSI.Q01" , "BSI.Q02" , "BSI.Q03" , "BSI.Q04" , "BSI.Q06" , "BSI.Q07" , "BSI.Q08" , "BSI.Q09" , "BSI.Q10" , "BSI.Q11" , "BSI.Q12" , "BSI.Q13" , "BSI.Q14" , "BSI.Q16" , "BSI.Q17" , "BSI.Q18" , "BSI.Q19" , "BSI.Q20" , "BSI.Q21" , "BSI.Q22" , "BSI.Q23" , "BSI.Q24" , "BSI.Q25" , "BSI.Q28" , "BSI.Q29" , "BSI.Q30" , "BSI.Q31" , "BSI.Q33" , "BSI.Q34" , "BSI.Q35" , "BSI.Q37" , "BSI.Q38" , "BSI.Q39" , "BSI.Q40" , "BSI.Q41" , "BSI.Q42" , "BSI.Q43" , "BSI.Q44" , "BSI.Q45" , "BSI.Q46" , "BSI.Q47" , "BSI.Q48" , "BSI.Q49" , "BSI.Q50" , "BSI.Q51" , "BSI.Q52" , "BSI.Q53")

rrtDcron <- round(psych::alpha(allds_item %>% select(starts_with("RRTmod")))$total$raw_alpha, 2)
BSI.generalCron <- round(psych::alpha(allds_item %>% select(all_of(BSI.general)))$total$raw_alpha, 2)
BSI.DepressionCron <- round(psych::alpha(allds_item %>% select(all_of(BSI.Depression)))$total$raw_alpha, 2)
CESDqCron <- round(psych::alpha(allds_item %>% select(all_of(CESDq)))$total$raw_alpha, 2)
DEQ6qCron <- round(psych::alpha(allds_item %>% select(all_of(DEQ6q)))$total$raw_alpha, 2)
RSESqCron <- round(psych::alpha(allds_item %>% select(all_of(RSESq)))$total$raw_alpha, 2)
fscrsHSCron <- round(psych::alpha(allds_item %>% select(all_of(fscrsHS)))$total$raw_alpha, 2)
fscrsRSCron <- round(psych::alpha(allds_item %>% select(all_of(fscrsRS)))$total$raw_alpha, 2)
fscrsISCron <- round(psych::alpha(allds_item %>% select(all_of(fscrsIS)))$total$raw_alpha, 2)
```


```{r, results='asis', include=includePrev}
# IC table
tribble(~measure,~`Cronbach\'s Alpha`,
        "SC-RRT" , rrtDcron,
        "BSI General" ,BSI.generalCron,
        "BSI Depression" , BSI.DepressionCron,
        "CESD" ,CESDqCron,
        "DEQ-SC6" ,DEQ6qCron,
        "FSCRS HS" ,fscrsHSCron,
        "FSCRS IS" ,fscrsISCron,
        "FSCRS RS" , fscrsRSCron,
        "RSES",RSESqCron
        ) %>% 
    papaja::apa_table(caption = "Internal Consistency",
                    # note = "* p < 0.05; ** p < 0.01; *** p < 0.001",
                    escape = F)
```

```{r}
# discriminant validity
RRTSC1 %$%
  psych::correct.cor(cor(matrix(c(RRT,rses),ncol = 2), use = "pairwise"),c(rrtDcron,RSESqCron))[1,2]
```

```{r}
# # in case I'll want to report the covariance estimates when the're in the same model
# model <- "
#   rses ~~ deq6
#   rses ~~ RRT
#   RRT ~~ deq6
# "
# library(lavaan)
# sem(model, RRTSC1) %>% summary()
```



```{r, include=F}
allds_computed_cen <- RRTSC1 %>% as_tibble() %>%  
  select(RRT , BSI.general , BSI.Depression , CESD = cesd , deq6 , RSES = rses , fscrsHS , fscrsIS , fscrsRS , female) %>% 
  mutate(across(where(is.numeric) & !female,~scale(.x, scale = F,center = T)))

allds_computed_scl <- allds_computed_cen %>% 
  mutate(across(where(is.numeric) & !female,~scale(.x, scale = T,center = T)))
```

```{r, include=F}
#these create excel files with the tables 
fit1 <- lm(data = allds_computed_scl , BSI.general    ~ RRT * deq6) 
fit2 <- lm(data = allds_computed_scl , BSI.Depression ~ RRT * deq6) 
fit3 <- lm(data = allds_computed_scl , CESD           ~ RRT * deq6) 


export_summs(fit1,fit2,fit3,
                     model.names = c("BSI Global", "BSI Depression", "CESD")
                     , to.file = "xlsx", file.name = "tables/lm_DEQ-SC6.xlsx"
                     )

#these create excel files with the tables 
fit1 <- lm(data = allds_computed_scl , BSI.general    ~ RRT * fscrsIS) 
fit2 <- lm(data = allds_computed_scl , BSI.Depression ~ RRT * fscrsIS) 
fit3 <- lm(data = allds_computed_scl , CESD           ~ RRT * fscrsIS) 


export_summs(fit1,fit2,fit3,
                     model.names = c("BSI Global", "BSI Depression", "CESD")
                     , to.file = "xlsx", file.name = "tables/lm_FSCRS_IS.xlsx"
                     )

#these create excel files with the tables 
fit1 <- lm(data = allds_computed_scl , BSI.general    ~ RRT * fscrsRS) 
fit2 <- lm(data = allds_computed_scl , BSI.Depression ~ RRT * fscrsRS) 
fit3 <- lm(data = allds_computed_scl , CESD           ~ RRT * fscrsRS) 


export_summs(fit1,fit2,fit3,
                     model.names = c("BSI Global", "BSI Depression", "CESD")
                     , to.file = "xlsx", file.name = "tables/lm_FSCRS_RS.xlsx"
                     )

#these create excel files with the tables 
fit1 <- lm(data = allds_computed_scl , BSI.general    ~ RRT * fscrsHS) 
fit2 <- lm(data = allds_computed_scl , BSI.Depression ~ RRT * fscrsHS) 
fit3 <- lm(data = allds_computed_scl , CESD           ~ RRT * fscrsHS) 


export_summs(fit1,fit2,fit3,
                     model.names = c("BSI Global", "BSI Depression", "CESD")
                     , to.file = "xlsx", file.name = "tables/lm_FSCRS_HS.xlsx"
                     )

p1 <- interact_plot(fit1,modx = "fscrsHS",pred = "RRT", x.label = "SC-RRT (z Score)" , y.label = "BSI Global (z Score)", legend.main = "FSCRS HS", colors = "Greys", main.title = "Simple Slopes", modx.values = "plus-minus") + papaja::theme_apa() + ylim(c(-2,2))
simslp <- sim_slopes(fit1,modx = "fscrsHS",pred = "RRT", jnplot = T, sig.color = "black", insig.color = "grey", title = "Johnson-Neyman", modx.values = "plus-minus")
s1 <- simslp$jnplot + labs(y = "Slope of SC-RRT" , x = "FSCRS HS (z Score)") + papaja::theme_apa() + theme(legend.title = element_blank())
simslp$slopes


```



```{r, include=F}
#these create excel files with the tables 
fit1 <- lm(data = allds_computed_scl , BSI.general    ~ RRT * deq6 * female) 
fit2 <- lm(data = allds_computed_scl , BSI.Depression ~ RRT * deq6 * female) 
fit3 <- lm(data = allds_computed_scl , CESD           ~ RRT * deq6 * female) 


parameters(fit1)
parameters(fit2)
parameters(fit3)

export_summs(fit1,fit2,fit3,
                     model.names = c("BSI Global", "BSI Depression", "CESD")
                     , to.file = "xlsx", file.name = "tables/lm_DEQ-SC6_sex.xlsx"
                     )


#these create excel files with the tables 
fit1 <- lm(data = allds_computed_scl , BSI.general    ~ RRT * fscrsIS * female) 
fit2 <- lm(data = allds_computed_scl , BSI.Depression ~ RRT * fscrsIS * female) 
fit3 <- lm(data = allds_computed_scl , CESD           ~ RRT * fscrsIS * female) 

parameters(fit1)
parameters(fit2)
parameters(fit3)

export_summs(fit1,fit2,fit3,
                     model.names = c("BSI Global", "BSI Depression", "CESD")
                     , to.file = "xlsx", file.name = "tables/lm_FSCRS_IS_sex.xlsx"
                     )

#these create excel files with the tables 
fit1 <- lm(data = allds_computed_scl , BSI.general    ~ RRT * fscrsRS * female) 
fit2 <- lm(data = allds_computed_scl , BSI.Depression ~ RRT * fscrsRS * female) 
fit3 <- lm(data = allds_computed_scl , CESD           ~ RRT * fscrsRS * female) 

parameters(fit1)
parameters(fit2)
parameters(fit3)

export_summs(fit1,fit2,fit3,
                     model.names = c("BSI Global", "BSI Depression", "CESD")
                     , to.file = "xlsx", file.name = "tables/lm_FSCRS_RS_sex.xlsx"
                     )

#these create excel files with the tables 
fit1 <- lm(data = allds_computed_scl , BSI.general    ~ RRT * fscrsHS * female) 
fit2 <- lm(data = allds_computed_scl , BSI.Depression ~ RRT * fscrsHS * female) 
fit3 <- lm(data = allds_computed_scl , CESD           ~ RRT * fscrsHS * female) 

parameters(fit1)
parameters(fit2)
parameters(fit3)

export_summs(fit1,fit2,fit3,
                     model.names = c("BSI Global", "BSI Depression", "CESD")
                     , to.file = "xlsx", file.name = "tables/lm_FSCRS_HS_sex.xlsx"
                     )

p2 <- interact_plot(fit1,modx = "fscrsHS",pred = "RRT", x.label = "SC-RRT (z Score)" , y.label = "BSI Global (z Score)", legend.main = "FSCRS HS", colors = "Greys", main.title = "Simple Slopes", modx.values = "plus-minus") + papaja::theme_apa() + ylim(c(-2,2))
simslp <- sim_slopes(fit1,modx = "fscrsHS",pred = "RRT", jnplot = T, sig.color = "black", insig.color = "grey", title = "Johnson-Neyman", modx.values = "plus-minus")
s2 <- simslp$jnplot + labs(y = "Slope of SC-RRT" , x = "FSCRS HS (z Score)") + papaja::theme_apa() + theme(legend.title = element_blank())
simslp$slopes

p3 <- interact_plot(fit2,modx = "fscrsHS",pred = "RRT", x.label = "SC-RRT (z Score)" , y.label = "BSI Depression (z Score)", legend.main = "FSCRS HS", colors = "Greys", main.title = "Simple Slopes", modx.values = "plus-minus") + papaja::theme_apa() + ylim(c(-2,2))
simslp <- sim_slopes(fit2,modx = "fscrsHS",pred = "RRT", jnplot = T, sig.color = "black", insig.color = "grey", title = "Johnson-Neyman", modx.values = "plus-minus")
s3 <- simslp$jnplot + labs(y = "Slope of SC-RRT" , x = "FSCRS HS (z Score)") + papaja::theme_apa() + theme(legend.title = element_blank())
simslp$slopes

ggsave(p1 + s1 + plot_annotation(tag_levels = 'A') + plot_layout(design = "AA##BB") , filename = "figures/figure1.png", width = 9.8, height = 5.2, units = "in")
ggsave(p2 + s2 + plot_annotation(tag_levels = 'A') + plot_layout(design = "AA##BB") , filename = "figures/figure2.png", width = 9.8, height = 5.2, units = "in")
ggsave(p3 + s3 + plot_annotation(tag_levels = 'A') + plot_layout(design = "AA##BB") , filename = "figures/figure3.png", width = 9.8, height = 5.2, units = "in")

```

