---
title: "The Self Reported Experiences - Self-Criticism (SRE-SC) – Validation of an Indirect Measure of Self-Criticism"
shorttitle: "Study 5 - Study Summary"
author: 
  - name          : "Michael Pinus"
    affiliation   : "1"
    corresponding : yes    # Define only one corresponding author
    address       : "Department of Psychology, Ben-Gurion University of the Negev, 800 Ben-Gurion Avenue, Beer-Sheva 84105, Israel"
    email         : "pinusm@post.bgu.ac.il"
  - name          : "Golan Shahar"
    affiliation   : "1"
affiliation:
  - id            : "1"
    institution   : "Department of Psychology, Ben-Gurion University of the Negev, Israel"
author_note: |
  Enter author note here.
abstract: |
  Enter abstract here. Each new line herein must be indented, like this line.
  
keywords          : "keywords"
wordcount         : "X"
figsintext        : no
figurelist        : no
tablelist         : no
footnotelist      : no
lineno            : yes
lang              : "en-US"
class             : "doc"
output            : papaja::apa6_word
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library("here")
library("magrittr")
library("lubridate")
library("tidyverse")
library("conflicted")
library("RColorBrewer")
library("BayesFactor")
library("parameters")
library("ggpubr")
library("patchwork")
library("psych")
library("see")
library("interactions")
library("corx")
library("effectsize")
library("jtools")
library("lavaan")
library("lme4")
library("cocron")
library("janitor")
library("Hmisc")
library("MuMIn")
library("papaja")
library("Mmisc")

includePrev = T

knitr::opts_chunk$set(echo = F,
                      tidy = "styler",
                      cache = TRUE)

options(digits = 3)

conflict_prefer("summarise", "dplyr", quiet = T)
conflict_prefer("filter", "dplyr", quiet = T)
conflict_prefer("select", "dplyr", quiet = T)
conflict_prefer("rename", "dplyr", quiet = T)
conflict_prefer("mutate", "dplyr", quiet = T)
conflict_prefer("here", "here", quiet = T)
conflict_prefer("extract", "tidyr", quiet = T)

alldsComputed <- fst::read_fst(here("data/alldsComputed.fst")) %>% janitor::remove_empty(c("cols","rows"))
alldsComputedWide <- fst::read_fst(here("data/alldsComputedWide.fst")) %>% janitor::remove_empty(c("cols","rows"))
alldsOnlyComputed <- fst::read_fst(here("data/alldsOnlyComputed.fst")) %>% janitor::remove_empty(c("cols","rows"))

lmmDataConstruct <- alldsOnlyComputed %>% select(wave , study, new.id,
                                         bsi.SC3,bsi.SC4guilt,bsi.SC4sin,bsi.SC5,
                                         bsi.Suic, bsi.DepressionNoSC, 
                                         bsi.generalNoSC3, bsi.generalNoSC4guilt,bsi.generalNoSC4sin,bsi.generalNoSC5,
                                         fscrs,deq.sc6,rses,cesd,rrs.brood) %>% 
  mutate_at(.vars = vars(-wave,-study,-new.id), scale, center = T, scale = T) %>%
  mutate_at(.vars = vars(-wave,-study,-new.id), as.numeric) %>% 
  {.}
```


```{r, include=includePrev}
## Participants 
completedPs <- alldsComputedWide %>% filter(!is.na(study)) %>% nrow()
alldsComputedWide %>% filter(!is.na(study)) %$% table(female,study,exclude = "") %>% ftable()
alldsComputedWide %>% filter(!is.na(study)) %$% table(female,exclude = "") 
alldsComputed %$% table(wave,study,exclude = "")
# note michael1 and michael2 were treated as single waves (so, despite the data originating from wave 2 in the studies, it shows as if there is no wave 2).
alldsComputed %>% filter(!is.na(study),!is.na(wave)) %$% table(wave,exclude = "")  # this one is misleading, because of the michael1,michael 2nd wave thing.

describe_distribution(alldsComputedWide %>% filter(!is.na(study)) %>% group_by(study) %>% select(age),iqr = F,range = F) %>% as.data.frame()
describe_distribution(alldsComputedWide %>% filter(!is.na(study)) %>% select(age),iqr = F,range = F) %>% as.data.frame()
```

```{r nonBSI IC}

IC_func <- function(x,fn="mean"){
  my_fn <- rowMeans
  if (fn == "sum") {
    my_fn <- rowSums
  }
  wave1df <- x %>% filter(wave == 1) %>% select(-wave)
  wave2df <- x %>% filter(wave == 2) %>% select(-wave)
  wave3df <- x %>% filter(wave == 3) %>% select(-wave)
  waveXdf <- x %>% select(-wave)
  
  wave1IC <- psych::alpha(wave1df ,check.keys=FALSE)
  wave1 = c(wave1IC %>% extract2("total") %>% extract2("raw_alpha") %>% round(2),
            wave1IC %>% extract2("item.stats") %>% extract2("n") %>% min(),
            wave1df %>% my_fn() %>% mean(na.rm = T)%>% round(2),
            wave1df %>% my_fn() %>% sd(na.rm = T)%>% round(2))
  wave2 = c()
  if (nrow(wave2df %>% remove_empty("rows"))>0) {
    wave2IC <- psych::alpha(wave2df ,check.keys=FALSE)
    wave2 = c(wave2IC %>% extract2("total") %>% extract2("raw_alpha") %>% round(2), 
              wave2IC %>% extract2("item.stats") %>% extract2("n") %>% min(),
            wave2df %>% my_fn() %>% mean(na.rm = T)%>% round(2),
            wave2df %>% my_fn() %>% sd(na.rm = T)%>% round(2))
  }
  wave3 = c()
  if (nrow(wave3df %>% remove_empty("rows"))>0) {
    wave3IC <- psych::alpha(wave3df ,check.keys=FALSE)
    wave3 = c(wave3IC %>% extract2("total") %>% extract2("raw_alpha") %>% round(2), 
              wave3IC %>% extract2("item.stats") %>% extract2("n") %>% min(),
            wave3df %>% my_fn() %>% mean(na.rm = T)%>% round(2),
            wave3df %>% my_fn() %>% sd(na.rm = T)%>% round(2))
  }

  waveXIC <- psych::alpha(waveXdf ,check.keys=FALSE)
  waveX = c(waveXIC %>% extract2("total") %>% extract2("raw_alpha") %>% round(2), 
                 waveXIC %>% extract2("item.stats") %>% extract2("n") %>% min(),
            waveXdf %>% my_fn() %>% mean(na.rm = T)%>% round(2),
            waveXdf %>% my_fn() %>% sd(na.rm = T)%>% round(2))
  
  list(wave1 = wave1,
       wave2 = wave2,
       wave3 = wave3,
       waveX = waveX)
}
#deq.sc6
alldsComputed %>% select(wave,sc1,sc2,sc3,sc4,sc5,sc6) %>% IC_func()
#fscrs.HS
alldsComputed %>% select(wave,fscrs9 , fscrs10 , fscrs12 , fscrs15 , fscrs22) %>% IC_func()
#fscrs.RS
alldsComputed %>% select(wave,fscrs3 , fscrs5 , fscrs8 , fscrs11 , fscrs13 , fscrs16 , fscrs19 , fscrs21) %>% IC_func()
#fscrs.IS
alldsComputed %>% select(wave,fscrs1 , fscrs2 , fscrs4 , fscrs6 , fscrs7 , fscrs14 , fscrs17 , fscrs18 , fscrs20) %>% IC_func()
# fscrs
alldsComputed %>% select(wave,fscrs1 , fscrs2 , fscrs4 , fscrs6 , fscrs7 , fscrs14 , fscrs17 , fscrs18 , fscrs20,
                         fscrs9 , fscrs10 , fscrs12 , fscrs15 , fscrs22,
                         fscrs3r,fscrs5r,fscrs8r,fscrs11r,fscrs13r,fscrs16r,fscrs19r,fscrs21r) %>% IC_func()

#rrs - mean and SD
alldsComputed %>% select(wave,rrs.brood) %>% na.omit %>% group_by(wave) %>% summarise(mean = mean(rrs.brood, na.rm = T), sd = sd(rrs.brood,na.rm = T),n=n()) %>%
  bind_rows(alldsComputed %>% select(wave,rrs.brood) %>% na.omit %>% summarise(mean = mean(rrs.brood, na.rm = T), sd = sd(rrs.brood,na.rm = T),n=n())) %>%
  remove_empty("rows") %>% round(2)

#rses # valid only for the IC not the mean and SD (because it does not include Schiller's sample)
alldsComputed %>% select(wave,rses1,rses3,rses4,rses7,rses10,rses2r,rses5r,rses6r,rses8r,rses9r) %>% IC_func()
#rses - mean and SD
alldsComputed %>% select(wave,rses) %>% na.omit %>% group_by(wave) %>% summarise(mean = mean(rses, na.rm = T), sd = sd(rses,na.rm = T),n=n()) %>%
  bind_rows(alldsComputed %>% select(wave,rses) %>% na.omit %>% summarise(mean = mean(rses, na.rm = T), sd = sd(rses,na.rm = T),n=n())) %>%
  remove_empty("rows") %>% round(2)

#cesd
alldsComputed %>% select(wave,cesd1,cesd2,cesd3,cesd5,cesd7,cesd9,cesd10,cesd11,cesd13,cesd14,cesd15,cesd17,cesd18,cesd19,cesd20,cesd4r,cesd8r,cesd12r,cesd16r) %>% IC_func(fn = "sum")

#bsi.SC3 
alldsComputed %>% select(wave, bsi22 , bsi48 , bsi50) %>% IC_func()
#bsi.SC4guilt 
alldsComputed %>% select(wave, bsi22 , bsi48 , bsi50, bsi52) %>% IC_func()
#bsi.SC4sin 
alldsComputed %>% select(wave, bsi22 , bsi48 , bsi50, bsi34) %>% IC_func()
#bsi.SC5 
alldsComputed %>% select(wave, bsi22 , bsi34, bsi48 , bsi50, bsi52) %>% IC_func()
# bsi.dep
alldsComputed %>% select(wave, bsi9 , bsi16 , bsi17 , bsi18 , bsi35 , bsi50, bsi20) %>% IC_func()
# bsi.dep - SC
alldsComputed %>% select(wave, bsi9 , bsi16 , bsi17 , bsi18 , bsi35 , bsi20) %>% IC_func()
#bsi.gen 
alldsComputed %>% select(wave,starts_with("bsi"), -starts_with("bsi.")) %>% IC_func()
#bsi.gen -SC3
alldsComputed %>% select(-bsi22 , -bsi48 , -bsi50) %>% 
  select(wave,starts_with("bsi"), -starts_with("bsi.")) %>% IC_func()
#bsi.gen -SC4guilt
alldsComputed %>% select(-bsi22 , -bsi48 , -bsi50, -bsi52) %>% 
  select(wave,starts_with("bsi"), -starts_with("bsi.")) %>% IC_func()
#bsi.gen -SC4sin
alldsComputed %>% select(-bsi22 , -bsi48 , -bsi50, -bsi34) %>% 
  select(wave,starts_with("bsi"), -starts_with("bsi.")) %>% IC_func()
#bsi.gen -SC5
alldsComputed %>% select(-bsi22 , -bsi34, -bsi48 , -bsi50, -bsi52) %>% 
  select(wave,starts_with("bsi"), -starts_with("bsi.")) %>% IC_func()

#bsi suicidality
alldsComputed %>% select(wave,bsi.Suic) %>% na.omit %>% group_by(wave) %>% summarise(mean = mean(bsi.Suic, na.rm = T), sd = sd(bsi.Suic,na.rm = T),n=n()) %>%
  bind_rows(alldsComputed %>% select(wave,bsi.Suic) %>% na.omit %>% summarise(mean = mean(bsi.Suic, na.rm = T), sd = sd(bsi.Suic,na.rm = T),n=n())) %>%
  remove_empty("rows") %>% round(2)

```


```{r retest, include=F}
bsi.SC5.wide <- alldsComputedWide %>% select(bsi22.t1 , bsi22.t2, bsi22.t3,
                                             bsi34.t1 , bsi34.t2, bsi34.t3,
                                             bsi48.t1 , bsi48.t2, bsi48.t3,
                                             bsi50.t1 , bsi50.t2, bsi50.t3,
                                             bsi52.t1 , bsi52.t2, bsi52.t3
                                             ) %>% mutate(
                                               wave1 = rowMeans(data.frame(bsi22.t1 , bsi34.t1, bsi48.t1 , bsi50.t1, bsi52.t1), na.rm = TRUE),
                                               wave2 = rowMeans(data.frame(bsi22.t2 , bsi34.t2, bsi48.t2 , bsi50.t2, bsi52.t2), na.rm = TRUE),
                                               wave3 = rowMeans(data.frame(bsi22.t3 , bsi34.t3, bsi48.t3 , bsi50.t3, bsi52.t3), na.rm = TRUE)
                                             ) %>%
                                              select(wave1,wave2,wave3)
bsi.SC4guilt.wide <- alldsComputedWide %>% select(bsi22.t1 , bsi22.t2, bsi22.t3,
                                             bsi48.t1 , bsi48.t2, bsi48.t3,
                                             bsi50.t1 , bsi50.t2, bsi50.t3,
                                             bsi52.t1 , bsi52.t2, bsi52.t3
                                             ) %>% mutate(
                                               wave1 = rowMeans(data.frame(bsi22.t1 , bsi48.t1 , bsi50.t1, bsi52.t1), na.rm = TRUE),
                                               wave2 = rowMeans(data.frame(bsi22.t2 , bsi48.t2 , bsi50.t2, bsi52.t2), na.rm = TRUE),
                                               wave3 = rowMeans(data.frame(bsi22.t3 , bsi48.t3 , bsi50.t3, bsi52.t3), na.rm = TRUE)
                                             ) %>%
                                              select(wave1,wave2,wave3)
bsi.SC4sin.wide <- alldsComputedWide %>% select(bsi22.t1 , bsi22.t2, bsi22.t3,
                                             bsi34.t1 , bsi34.t2, bsi34.t3,
                                             bsi48.t1 , bsi48.t2, bsi48.t3,
                                             bsi50.t1 , bsi50.t2, bsi50.t3
                                             ) %>% mutate(
                                               wave1 = rowMeans(data.frame(bsi22.t1 , bsi34.t1, bsi48.t1 , bsi50.t1), na.rm = TRUE),
                                               wave2 = rowMeans(data.frame(bsi22.t2 , bsi34.t2, bsi48.t2 , bsi50.t2), na.rm = TRUE),
                                               wave3 = rowMeans(data.frame(bsi22.t3 , bsi34.t3, bsi48.t3 , bsi50.t3), na.rm = TRUE)
                                             ) %>%
                                              select(wave1,wave2,wave3)
bsi.SC3.wide <- alldsComputedWide %>% select(bsi22.t1 , bsi22.t2, bsi22.t3,
                                             bsi48.t1 , bsi48.t2, bsi48.t3,
                                             bsi50.t1 , bsi50.t2, bsi50.t3
                                             ) %>% mutate(
                                               wave1 = rowMeans(data.frame(bsi22.t1 , bsi48.t1 , bsi50.t1), na.rm = TRUE),
                                               wave2 = rowMeans(data.frame(bsi22.t2 , bsi48.t2 , bsi50.t2), na.rm = TRUE),
                                               wave3 = rowMeans(data.frame(bsi22.t3 , bsi48.t3 , bsi50.t3), na.rm = TRUE)
                                             ) %>%
                                              select(wave1,wave2,wave3)

bsi.gen.wide <- alldsComputedWide %>% select(wave1 = bsi.general.t1,
                                             wave2 = bsi.general.t2,
                                             wave3 = bsi.general.t3)

bsi.dep.wide <- alldsComputedWide %>% select(wave1 = bsi.Depression.t1,
                                             wave2 = bsi.Depression.t2,
                                             wave3 = bsi.Depression.t3)

bsi.suic.wide <- alldsComputedWide %>% select(wave1 = bsi.Suic.t1,
                                             wave2 = bsi.Suic.t2,
                                             wave3 = bsi.Suic.t3)
```


```{r retestReportFunction, include=F}
# This section provides formatting a correlation matrix into a table with 5 columns containing x,y,r,p,n
flattenCorrMatrix <- function(cormat, pmat, nmat) {
  ut <- upper.tri(cormat)
  data.frame(
    row = rownames(cormat)[row(cormat)[ut]],
    column = rownames(cormat)[col(cormat)[ut]],
    cor  =(cormat)[ut],
    p = pmat[ut],
    n = nmat[ut]
    )
}

flatCor <-
    function(df){
      result <- Hmisc::rcorr(df %>% as.matrix())
      combined <- flattenCorrMatrix(result$r, result$P, result$n)
      return(combined)
    }

```


```{r retestReport, include=T, results='asis'}
namesforlist <-c( "SC-BSR3",rep(" ",2), 
                  "SC-BSR4guilt",rep(" ",2),
                  "SC-BSR4sin", rep(" ",2),
                  "SC-BSR5",rep(" ",2) ,
                  "BSI Depression",rep(" ",2) ,
                  "BSI Gloabl",rep(" ",2),
                  "BSI Suicidality",rep(" ",2)
                  )

retestTable <-
    bind_cols(tibble(subscale = namesforlist),
            bind_rows(
              flatCor(bsi.SC3.wide),
              flatCor(bsi.SC4guilt.wide),
              flatCor(bsi.SC4sin.wide),
              flatCor(bsi.SC5.wide),
              flatCor(bsi.dep.wide),
              flatCor(bsi.gen.wide),
              flatCor(bsi.suic.wide)
              )
  ) %>%
   mutate(p = pvalue.correct(p),
          row = as.character(row),
          column = as.character(column),
          comp = paste0(capitalize(as.character(row)),"-",capitalize(column))
          ) %>%
           select(-row,-column) %>%
           select(subscale, comp, cor,p,n)

apa_table(retestTable, caption = "caption",
          note = "note",
          col.names = c("Subscale" , "Waves","r","p","n")
          ) 

```


```{r LMM construct BSI.SC3}
lme4::lmer(formula = bsi.generalNoSC3 ~ 1 + bsi.SC3 + ( 1 | new.id )+( 1 | study )+( 1 | wave ),
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)

lme4::lmer(formula = bsi.DepressionNoSC ~ 1 + bsi.SC3 + ( 1 | new.id )+( 1 | study ) +( 1 | wave ),
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)

lme4::lmer(formula = bsi.Suic ~ 1 + bsi.SC3 + ( 1 | new.id )+( 1 | study )+( 1 | wave ),
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)
```

```{r LMM construct BSI.SC4Gulit}
lme4::lmer(formula = bsi.generalNoSC4guilt ~ 1 + bsi.SC4guilt + ( 1 | new.id )+( 1 | study )+( 1 | wave ),
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)

lme4::lmer(formula = bsi.DepressionNoSC ~ 1 + bsi.SC4guilt + ( 1 | new.id )+( 1 | study ) +( 1 | wave ),
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)

lme4::lmer(formula = bsi.Suic ~ 1 + bsi.SC4guilt + ( 1 | new.id )+( 1 | study ) +( 1 | wave ),
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)
```

```{r LMM construct BSI.SC4Sin}
lme4::lmer(formula = bsi.generalNoSC4sin ~ 1 + bsi.SC4sin + ( 1 | new.id )+( 1 | study )+( 1 | wave ),
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)

lme4::lmer(formula = bsi.DepressionNoSC ~ 1 + bsi.SC4sin + ( 1 | new.id )+( 1 | study ) +( 1 | wave ),
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)

lme4::lmer(formula = bsi.Suic ~ 1 + bsi.SC4sin + ( 1 | new.id )+( 1 | study ) +( 1 | wave ),
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)
```

```{r LMM construct BSI.SC5}
lme4::lmer(formula = bsi.generalNoSC5 ~ 1 + bsi.SC5 + ( 1 | new.id )+( 1 | study ) + (1|wave),
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)

lme4::lmer(formula = bsi.DepressionNoSC ~ 1 + bsi.SC5 + ( 1 | new.id ) +( 1 | study ) + (1|wave),
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)

lme4::lmer(formula = bsi.Suic ~ 1 + bsi.SC5 + ( 1 | new.id )+( 1 | study )+ (1|wave),
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)
```


```{r LMM construct BSI.SC3 non BSI}
#remove 'wave'
lme4::lmer(formula = deq.sc6 ~ 1 + bsi.SC3 + ( 1 | new.id )+( 1 | study ) ,
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)

lme4::lmer(formula = fscrs ~ 1 + bsi.SC3 + ( 1 | new.id )+( 1 | study ) +( 1 | wave ) ,
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)

# remove 'wave' and 'Study' for singularity.
lme4::lmer(formula = cesd ~ 1 + bsi.SC3 + + ( 1 | new.id ) ,
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)

# only 1 study, so dropping study
lme4::lmer(formula = rrs.brood ~ 1 + bsi.SC3 + ( 1 | new.id )+( 1 | wave ),
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)

lme4::lmer(formula = rses ~ 1 + bsi.SC3 + ( 1 | new.id )+( 1 | wave ) +( 1 | study ),
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)

```


```{r LMM construct BSI.SC4guilt non BSI}
#remove wave
lme4::lmer(formula = deq.sc6 ~ 1 + bsi.SC4guilt + ( 1 | new.id )+( 1 | study ),
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)

lme4::lmer(formula = fscrs ~ 1 + bsi.SC4guilt + ( 1 | new.id )+( 1 | study ) +( 1 | wave ),
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)

# remove 'wave' and 'Study' for singularity
lme4::lmer(formula = cesd ~ 1 + bsi.SC4guilt+ ( 1 | new.id ),
   data = lmmDataConstruct,
   REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)

# only 1 study, so dropping study
lme4::lmer(formula = rrs.brood ~ 1 + bsi.SC4guilt + ( 1 | new.id )+( 1 | wave ),
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)

lme4::lmer(formula = rses ~ 1 + bsi.SC4guilt + ( 1 | new.id )+( 1 | wave )+( 1 | study ) ,
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)
```

```{r LMM construct BSI.SC4sin non BSI}
#remove wave
lme4::lmer(formula = deq.sc6 ~ 1 + bsi.SC4sin + ( 1 | new.id )+(1|study),
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)

lme4::lmer(formula = fscrs ~ 1 + bsi.SC4sin + ( 1 | new.id ) +( 1 | study ) +( 1 | wave ),
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)

# remove 'wave' and 'Study' for singularity
lme4::lmer(formula = cesd ~ 1 + bsi.SC4sin  + ( 1 | new.id ) ,
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)

# only 1 study, so dropping study
lme4::lmer(formula = rrs.brood ~ 1 + bsi.SC4sin + ( 1 | new.id )+( 1 | wave ),
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)

lme4::lmer(formula = rses ~ 1 + bsi.SC4sin + ( 1 | new.id )+( 1 | wave )+( 1 | study ),
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)
```

```{r LMM construct BSI.SC5 non BSI}
#remove wave
lme4::lmer(formula = deq.sc6 ~ 1 + bsi.SC5 + ( 1 | new.id )+(1|study),
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)

lme4::lmer(formula = fscrs ~ 1 + bsi.SC5 + ( 1 | new.id ) +( 1 | study ) +( 1 | wave ),
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)

# remove 'wave' and 'Study' for singularity
lme4::lmer(formula = cesd ~ 1 + bsi.SC5  + ( 1 | new.id ) ,
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)

# only 1 study, so dropping study
lme4::lmer(formula = rrs.brood ~ 1 + bsi.SC5 + ( 1 | new.id )+( 1 | wave ),
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)

lme4::lmer(formula = rses ~ 1 + bsi.SC5 + ( 1 | new.id )+( 1 | wave )+( 1 | study ),
    data = lmmDataConstruct,
    REML = F) %>% jtools::summ() %>% extract2("coeftable") %>% round(2)

```


```{r disattenuated construct function}
trim_output <- function(.,x = "deq.sc6") {
  jtools::summ(.) %>% extract2("coeftable") %>% round(2) %>% as.data.frame() %>% rownames_to_column("eff") %>% filter(eff == x)
}
```


```{r disattenuated construct deq6}
#for all, no wave to avoid singular fit
lme4::lmer(formula = bsi.SC3 ~ 1 + deq.sc6 + ( 1 | new.id )+ ( 1 | study ) +  bsi.generalNoSC3  + bsi.DepressionNoSC,
    data = lmmDataConstruct %>% filter(!is.na(bsi.SC3)),
    REML = F) %>% trim_output("deq.sc6")

lme4::lmer(formula = bsi.SC4guilt ~ 1 + deq.sc6 + ( 1 | new.id )+ ( 1 | study ) +  bsi.generalNoSC4guilt  + bsi.DepressionNoSC,
    data = lmmDataConstruct %>% filter(!is.na(bsi.SC4guilt)),
    REML = F) %>% trim_output("deq.sc6")

lme4::lmer(formula = bsi.SC4sin ~ 1 + deq.sc6 + ( 1 | new.id )+ ( 1 | study ) +  bsi.generalNoSC4sin  + bsi.DepressionNoSC,
    data = lmmDataConstruct %>% filter(!is.na(bsi.SC4sin)),
    REML = F) %>% trim_output("deq.sc6")

lme4::lmer(formula = bsi.SC5 ~ 1 + deq.sc6 + ( 1 | new.id )+ ( 1 | study ) +  bsi.generalNoSC5  + bsi.DepressionNoSC,
    data = lmmDataConstruct %>% filter(!is.na(bsi.SC5)),
    REML = F) %>% trim_output("deq.sc6")

```

```{r disattenuated construct fscrs}
lme4::lmer(formula = bsi.SC3 ~ 1 + fscrs + ( 1 | new.id )+ ( 1 | study ) +  bsi.generalNoSC3  + bsi.DepressionNoSC + ( 1 | wave ),
    data = lmmDataConstruct %>% filter(!is.na(bsi.SC3)),
    REML = F) %>% trim_output("fscrs")

lme4::lmer(formula = bsi.SC4guilt ~ 1 + fscrs + ( 1 | new.id )+ ( 1 | study ) +  bsi.generalNoSC4guilt  + bsi.DepressionNoSC + ( 1 | wave ),
    data = lmmDataConstruct %>% filter(!is.na(bsi.SC4guilt)),
    REML = F) %>% trim_output("fscrs")

lme4::lmer(formula = bsi.SC4sin ~ 1 + fscrs + ( 1 | new.id )+ ( 1 | study ) +  bsi.generalNoSC4sin  + bsi.DepressionNoSC + ( 1 | wave ),
    data = lmmDataConstruct %>% filter(!is.na(bsi.SC4sin)),
    REML = F) %>% trim_output("fscrs")

#no wave to avoid converges issues
lme4::lmer(formula = bsi.SC5 ~ 1 + fscrs + ( 1 | new.id ) + ( 1 | study ) +  bsi.generalNoSC5  + bsi.DepressionNoSC ,
    data = lmmDataConstruct %>% filter(!is.na(bsi.SC5)),
    REML = F) %>% trim_output("fscrs")
```


```{r LMM Brood}
modelBroodTrait <-
    lme4::lmer(formula = rrs.brood ~ 1 + fscrs + deq.sc6 + ( 1 | new.id )+( 1 | wave ),
    data = lmmDataConstruct %>% filter(!is.na(bsi.SC3)),
    REML = F)
# Only one study used the RRS, so I'll drop Study

modelBroodSC3 <-
  update(modelBroodTrait, formula =  . ~ . + bsi.SC3)
modelBroodSC4guilt <-
  update(modelBroodTrait, formula =  . ~ . + bsi.SC4guilt)
modelBroodSC4sin <-
  update(modelBroodTrait, formula =  . ~ . + bsi.SC4sin)
modelBroodSC5 <-
  update(modelBroodTrait, formula =  . ~ . + bsi.SC5)
jtools::export_summs(modelBroodTrait,modelBroodSC3,modelBroodSC4guilt,modelBroodSC4sin,modelBroodSC5, scale = F,
                     to.file = "xlsx", file.name = "tables/brood.xlsx",
                     model.names = c("Trait Measures","BSI-SC3","BSI-SC4 Guilt","BSI-SC4 Sin","BSI-SC5")) 

#get R^2 diff
(MuMIn::r.squaredGLMM(modelBroodSC3)-MuMIn::r.squaredGLMM(modelBroodTrait)) %>% round(2)
(MuMIn::r.squaredGLMM(modelBroodSC4guilt)-MuMIn::r.squaredGLMM(modelBroodTrait)) %>% round(2)
(MuMIn::r.squaredGLMM(modelBroodSC4sin)-MuMIn::r.squaredGLMM(modelBroodTrait)) %>% round(2)
(MuMIn::r.squaredGLMM(modelBroodSC5)-MuMIn::r.squaredGLMM(modelBroodTrait)) %>% round(2)


#get sig for model diff
anova(modelBroodTrait,modelBroodSC3)$`Pr(>Chisq)`[2]
anova(modelBroodTrait,modelBroodSC4guilt)$`Pr(>Chisq)`[2]
anova(modelBroodTrait,modelBroodSC4sin)$`Pr(>Chisq)`[2]
anova(modelBroodTrait,modelBroodSC5)$`Pr(>Chisq)`[2]

model.sel(modelBroodTrait,modelBroodSC3, rank = "BIC") 
model.sel(modelBroodTrait,modelBroodSC4guilt, rank = "BIC") 
model.sel(modelBroodTrait,modelBroodSC4sin, rank = "BIC") 
model.sel(modelBroodTrait,modelBroodSC5, rank = "BIC") 
```


```{r LMM BSI depression}
# that's singular, so I'll drop wave
modelDepressionTrait <-
    lme4::lmer(formula = bsi.DepressionNoSC ~ 1 + fscrs + deq.sc6 + ( 1 | new.id )+( 1 | study ),
    data = lmmDataConstruct,
    REML = F)

modelDepressionSC3 <-
  update(modelDepressionTrait, formula =  . ~ . + bsi.SC3)
modelDepressionSC4guilt <-
  update(modelDepressionTrait, formula =  . ~ . + bsi.SC4guilt)
modelDepressionSC4sin <-
  update(modelDepressionTrait, formula =  . ~ . + bsi.SC4sin)
modelDepressionSC5 <-
  update(modelDepressionTrait, formula =  . ~ . + bsi.SC5)
jtools::export_summs(modelDepressionTrait,modelDepressionSC3,modelDepressionSC4guilt,modelDepressionSC4sin,modelDepressionSC5, scale = TRUE,
                     to.file = "xlsx", file.name = "tables/BSIdep.xlsx",
                     model.names = c("Trait Measures","BSI-SC3","BSI-SC4 Guilt","BSI-SC4 Sin","BSI-SC5"))

#get R^2 diff
(MuMIn::r.squaredGLMM(modelDepressionSC3)-MuMIn::r.squaredGLMM(modelDepressionTrait)) %>% round(2)
(MuMIn::r.squaredGLMM(modelDepressionSC4guilt)-MuMIn::r.squaredGLMM(modelDepressionTrait)) %>% round(2)
(MuMIn::r.squaredGLMM(modelDepressionSC4sin)-MuMIn::r.squaredGLMM(modelDepressionTrait)) %>% round(2)
(MuMIn::r.squaredGLMM(modelDepressionSC5)-MuMIn::r.squaredGLMM(modelDepressionTrait)) %>% round(2)

#get sig for model diff
anova(modelDepressionTrait,modelDepressionSC3)$`Pr(>Chisq)`[2]
anova(modelDepressionTrait,modelDepressionSC4guilt)$`Pr(>Chisq)`[2]
anova(modelDepressionTrait,modelDepressionSC4sin)$`Pr(>Chisq)`[2]
anova(modelDepressionTrait,modelDepressionSC5)$`Pr(>Chisq)`[2]

model.sel(modelDepressionTrait,modelDepressionSC3, rank = "BIC") 
model.sel(modelDepressionTrait,modelDepressionSC4guilt, rank = "BIC") 
model.sel(modelDepressionTrait,modelDepressionSC4sin, rank = "BIC") 
model.sel(modelDepressionTrait,modelDepressionSC5, rank = "BIC") 
```

```{r LMM BSI global}
# that's singular, so I'll drop wave
modelGlobalTrait <-
    lme4::lmer(formula = bsi.generalNoSC5 ~ 1 + fscrs + deq.sc6 + ( 1 | new.id )+( 1 | study ),
    data = lmmDataConstruct,
    REML = F)

modelGlobalSC3 <-
  update(modelGlobalTrait, formula =  . ~ . + bsi.SC3)
modelGlobalSC4guilt <-
  update(modelGlobalTrait, formula =  . ~ . + bsi.SC4guilt)
modelGlobalSC4sin <-
  update(modelGlobalTrait, formula =  . ~ . + bsi.SC4sin)
modelGlobalSC5 <-
  update(modelGlobalTrait, formula =  . ~ . + bsi.SC5)
jtools::export_summs(modelGlobalTrait,modelGlobalSC3,modelGlobalSC4guilt,modelGlobalSC4sin,modelGlobalSC5,
                     to.file = "xlsx", file.name = "tables/BSIGlobal.xlsx",
                     model.names = c("Trait Measures","BSI-SC3","BSI-SC4 Guilt","BSI-SC4 Sin","BSI-SC5"))

#get R^2 diff
(MuMIn::r.squaredGLMM(modelGlobalSC3)-MuMIn::r.squaredGLMM(modelGlobalTrait)) %>% round(2)
(MuMIn::r.squaredGLMM(modelGlobalSC4guilt)-MuMIn::r.squaredGLMM(modelGlobalTrait)) %>% round(2)
(MuMIn::r.squaredGLMM(modelGlobalSC4sin)-MuMIn::r.squaredGLMM(modelGlobalTrait)) %>% round(2)
(MuMIn::r.squaredGLMM(modelGlobalSC5)-MuMIn::r.squaredGLMM(modelGlobalTrait)) %>% round(2)

#get sig for model diff
anova(modelGlobalTrait,modelGlobalSC3)$`Pr(>Chisq)`[2]
anova(modelGlobalTrait,modelGlobalSC4guilt)$`Pr(>Chisq)`[2]
anova(modelGlobalTrait,modelGlobalSC4sin)$`Pr(>Chisq)`[2]
anova(modelGlobalTrait,modelGlobalSC5)$`Pr(>Chisq)`[2]

model.sel(modelGlobalTrait,modelGlobalSC3, rank = "BIC") 
model.sel(modelGlobalTrait,modelGlobalSC4guilt, rank = "BIC") 
model.sel(modelGlobalTrait,modelGlobalSC4sin, rank = "BIC") 
model.sel(modelGlobalTrait,modelGlobalSC5, rank = "BIC") 
```

```{r LMM BSI Suicidality}
modelSuicTrait <-
    lme4::lmer(formula = bsi.Suic ~ 1 + fscrs + deq.sc6 + ( 1 | new.id )+( 1 | study )+( 1 | wave ),
    data = lmmDataConstruct,
    REML = F)

modelSuicSC3 <-
  update(modelSuicTrait, formula =  . ~ . + bsi.SC3)
modelSuicSC4guilt <-
  update(modelSuicTrait, formula =  . ~ . + bsi.SC4guilt)
modelSuicSC4sin <-
  update(modelSuicTrait, formula =  . ~ . + bsi.SC4sin)
modelSuicSC5 <-
  update(modelSuicTrait, formula =  . ~ . + bsi.SC5)
jtools::export_summs(modelSuicTrait,modelSuicSC3,modelSuicSC4guilt,modelSuicSC4sin,modelSuicSC5,
                     to.file = "xlsx", file.name = "tables/BSISuic.xlsx",
                     model.names = c("Trait Measures","BSI-SC3","BSI-SC4 Guilt","BSI-SC4 Sin","BSI-SC5"))

#get R^2 diff
(MuMIn::r.squaredGLMM(modelSuicSC3)-MuMIn::r.squaredGLMM(modelSuicTrait)) %>% round(2)
(MuMIn::r.squaredGLMM(modelSuicSC4guilt)-MuMIn::r.squaredGLMM(modelSuicTrait)) %>% round(2)
(MuMIn::r.squaredGLMM(modelSuicSC4sin)-MuMIn::r.squaredGLMM(modelSuicTrait)) %>% round(2)
(MuMIn::r.squaredGLMM(modelSuicSC5)-MuMIn::r.squaredGLMM(modelSuicTrait)) %>% round(2)

#get sig for model diff
anova(modelSuicTrait,modelSuicSC3)$`Pr(>Chisq)`[2]
anova(modelSuicTrait,modelSuicSC4guilt)$`Pr(>Chisq)`[2]
anova(modelSuicTrait,modelSuicSC4sin)$`Pr(>Chisq)`[2]
anova(modelSuicTrait,modelSuicSC5)$`Pr(>Chisq)`[2]

model.sel(modelSuicTrait,modelSuicSC3, rank = "BIC") 
model.sel(modelSuicTrait,modelSuicSC4guilt, rank = "BIC") 
model.sel(modelSuicTrait,modelSuicSC4sin, rank = "BIC") 
model.sel(modelSuicTrait,modelSuicSC5, rank = "BIC") 
```


```{r LMM CESD}
# that's singular, so I'll drop wave
# Only one wave used the CESD with DEQ.SC6, but two wave used FSCRS, so I'll drop DEQ.SC6 as lmer compalins about this
modelCesdTrait <-
    lme4::lmer(formula = cesd ~ 1 + fscrs + ( 1 | new.id )+( 1 | study ),
    data = lmmDataConstruct ,
    REML = F)


modelCesdSC3 <-
  update(modelCesdTrait, formula =  . ~ . + bsi.SC3)
modelCesdSC4guilt <-
  update(modelCesdTrait, formula =  . ~ . + bsi.SC4guilt)
modelCesdSC4sin <-
  update(modelCesdTrait, formula =  . ~ . + bsi.SC4sin)
modelCesdSC5 <-
  update(modelCesdTrait, formula =  . ~ . + bsi.SC5)
jtools::export_summs(modelCesdTrait,modelCesdSC3,modelCesdSC4guilt,modelCesdSC4sin,modelCesdSC5,
                     to.file = "xlsx", file.name = "tables/CESD.xlsx",
                     model.names = c("Trait Measures","BSI-SC3","BSI-SC4 Guilt","BSI-SC4 Sin","BSI-SC5"))

#get R^2 diff
(MuMIn::r.squaredGLMM(modelCesdSC3)-MuMIn::r.squaredGLMM(modelCesdTrait)) %>% round(2)
(MuMIn::r.squaredGLMM(modelCesdSC4guilt)-MuMIn::r.squaredGLMM(modelCesdTrait)) %>% round(2)
(MuMIn::r.squaredGLMM(modelCesdSC4sin)-MuMIn::r.squaredGLMM(modelCesdTrait)) %>% round(2)
(MuMIn::r.squaredGLMM(modelCesdSC5)-MuMIn::r.squaredGLMM(modelCesdTrait)) %>% round(2)

#get sig for model diff
anova(modelCesdTrait,modelCesdSC3)$`Pr(>Chisq)`[2]
anova(modelCesdTrait,modelCesdSC4guilt)$`Pr(>Chisq)`[2]
anova(modelCesdTrait,modelCesdSC4sin)$`Pr(>Chisq)`[2]
anova(modelCesdTrait,modelCesdSC5)$`Pr(>Chisq)`[2]

model.sel(modelCesdTrait,modelCesdSC3, rank = "BIC") 
model.sel(modelCesdTrait,modelCesdSC4guilt, rank = "BIC") 
model.sel(modelCesdTrait,modelCesdSC4sin, rank = "BIC") 
model.sel(modelCesdTrait,modelCesdSC5, rank = "BIC") 
```

```{r retest by study}
## 1-2 waves
## to get the N of the correlations, change extract2("r") to extract2("n") 
alldsComputedWide %>% select(study,starts_with("bsi.SC")) %>% 
  filter(study == "Michael3") %>% 
  select(-study) %>%  
  corx::corx(x = c("bsi.SC5.t1",
                   "bsi.SC3.t1",
                   "bsi.SC4guilt.t1",
                   "bsi.SC4sin.t1"),
             y = c("bsi.SC5.t2",
                   "bsi.SC3.t2",
                   "bsi.SC4guilt.t2",
                   "bsi.SC4sin.t2")) %>% extract2("r") %>% diag() %>% round(2)

alldsComputedWide %>% select(study,starts_with("bsi.SC")) %>% 
  filter(study == "Dana1") %>% 
  select(-study) %>%  
  corx::corx(x = c("bsi.SC5.t1",
                   "bsi.SC3.t1",
                   "bsi.SC4guilt.t1",
                   "bsi.SC4sin.t1"),
             y = c("bsi.SC5.t2",
                   "bsi.SC3.t2",
                   "bsi.SC4guilt.t2",
                   "bsi.SC4sin.t2")) %>% extract2("r") %>% diag() %>% round(2)

alldsComputedWide %>% select(study,starts_with("bsi.SC")) %>% 
  filter(study == "Nirit1") %>% 
  select(-study) %>%  
  corx::corx(x = c("bsi.SC5.t1",
                   "bsi.SC3.t1",
                   "bsi.SC4guilt.t1",
                   "bsi.SC4sin.t1"),
             y = c("bsi.SC5.t2",
                   "bsi.SC3.t2",
                   "bsi.SC4guilt.t2",
                   "bsi.SC4sin.t2")) %>% extract2("r") %>% diag() %>% round(2)

alldsComputedWide %>% select(study,starts_with("bsi.SC")) %>% 
  filter(study == "Moran") %>% 
  select(-study) %>%  
  corx::corx(x = c("bsi.SC5.t1",
                   "bsi.SC3.t1",
                   "bsi.SC4guilt.t1",
                   "bsi.SC4sin.t1"),
             y = c("bsi.SC5.t2",
                   "bsi.SC3.t2",
                   "bsi.SC4guilt.t2",
                   "bsi.SC4sin.t2")) %>% extract2("r") %>% diag() %>% round(2)

## waves 1-3
alldsComputedWide %>% select(study,starts_with("bsi.SC")) %>% 
  filter(study == "Moran") %>% 
  select(-study) %>%  
  corx::corx(x = c("bsi.SC5.t1",
                   "bsi.SC3.t1",
                   "bsi.SC4guilt.t1",
                   "bsi.SC4sin.t1"),
             y = c("bsi.SC5.t3",
                   "bsi.SC3.t3",
                   "bsi.SC4guilt.t3",
                   "bsi.SC4sin.t3")) %>% extract2("r") %>% diag() %>% round(2)

## waves 2-3
alldsComputedWide %>% select(study,starts_with("bsi.SC")) %>% 
  filter(study == "Moran") %>% 
  select(-study) %>%  
  corx::corx(x = c("bsi.SC5.t2",
                   "bsi.SC3.t2",
                   "bsi.SC4guilt.t2",
                   "bsi.SC4sin.t2"),
             y = c("bsi.SC5.t3",
                   "bsi.SC3.t3",
                   "bsi.SC4guilt.t3",
                   "bsi.SC4sin.t3")) %>% extract2("r") %>% diag() %>% round(2)

```

